version: '3.8'
services:
  solana-testnet:
    image: solanalabs/solana:v1.16.10
    command: solana-test-validator
    ports:
      - "8899:8899"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8899"]
      interval: 10s
      timeout: 5s
      retries: 5

  eremos-agent:
    build: .
    environment:
      - SOLANA_RPC_URL=http://solana-testnet:8899
    depends_on:
      - solana-testnet
    volumes:
      - ./examples:/app/examples
    command: npm run demo
