name: 💬 General Issue
description: General questions or discussions
title: "[General]: "
labels: ["question"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Question
        - Discussion
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to discuss?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any relevant background
