name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Validate package.json
      run: node -e "console.log('✅ package.json is valid JSON')"
    
    - name: Check for required files
      run: |
        echo "Checking for required files..."
        test -f package.json && echo "✅ package.json exists"
        test -f README.md && echo "✅ README.md exists"
        test -f LICENSE && echo "✅ LICENSE exists"
        test -d agents && echo "✅ agents/ directory exists"
        test -d types && echo "✅ types/ directory exists"
        test -d utils && echo "✅ utils/ directory exists"
    
    - name: Test Docker build
      run: docker build -t eremos-test .
    
    - name: Comment on PR
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🤖 **Eremos CI/CD Check**: All infrastructure validation passed! ✅'
          })